name: Atualiza README com GitHub Stats

on:
  schedule:
    - cron: '0 12 * * *' # todo dia ao meio-dia (horário UTC)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        uses: anuraghazra/github-readme-stats@master
        with:
          username: UmVitorAleatorio
          show_icons: true
          theme: dark
          count_private: true
          hide_border: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
